= NetPlan IoT Satellite

Der Satellite ist ein Endpoint im lokalen Netz des Benutzers, um ein Monitoring zu ermöglichen.
Dieser Satellite ist jedoch von außen direkt nicht erreichbar, weshalb er über das Internet eine Websocket Verbindung aufbauen muss.
Nachdem eine Verbindung mit der Cloud hergestellt wurde, erhält der Satellite seine Konfiguration.
Anschließend weiß er, welche Geräte mit welchen Metriken und in welchen Intervallen er abfragen muss.
Sofern ein neuer Metric Record ermittelt wurde, meldet er dies der Cloud.

== Initial Config / Renewal Flow

Um die initiale Konfiguration des Satellites zu erhalten, muss sich dieser erst gegen das Cloud-Backend authentifizieren.
So lassen sich bspw. die Satellites erst für einen bestimmten Account freischalten, um einen möglichen "Angriff" blockieren zu können.

[plantuml,Config,svg]
....
partition Satellite {
    (*) --> "Open Websocket"
    --> Send AUTHENTICATE event
}

partition Cloud {
    --> Check Token
    if "" then
        -->[Valid] Send CONFIG event
    else
        -->[Invalid] (*)
    endif
}

partition Satellite {
    "Send CONFIG event" --> Apply Config
    -.->[renew] Send AUTHENTICATE event
}
....

