name: Build and Push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Sources
      - name: Checkout Sources
        uses: actions/checkout@v2

      # Set Version
      - name: Set Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Init JVM
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Init settings.xml for Maven Build
      - name: Generate settings.xml
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: '[{"id": "default", "username": "${{ secrets.nexus_user }}", "password": "${{ secrets.nexus_password }}"}]'
          mirrors: '[{"id": "default", "name": "default", "mirrorOf": "*", "url": "https://nexus.conceptive.io/repository/maven-public/"}]'

      # Build all modules with tests enabled
      - name: Build JVM Mode
        run: mvn -B clean install

      # Login to Nexus
      - uses: azure/docker-login@v1
        with:
          login-server: images.conceptive.io
          username: ${{ secrets.nexus_user }}
          password: ${{ secrets.nexus_password }}

      # Create Docker Image
      - name: Create Image
        working-directory: ./satellite
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t images.conceptive.io/homestack.satellite:latest -t images.conceptive.io/homestack.satellite:${{ env.RELEASE_VERSION }} .

      # Push Docker Image
      - name: Push Image
        working-directory: ./satellite
        run: |
          docker push images.conceptive.io/homestack.satellite:latest
          docker push images.conceptive.io/homestack.satellite:${{ env.RELEASE_VERSION }}
